### ISSUE TITLE
Files Do not Publish

### ISSUE THREAD

**Issue by WaltDisneyWorld** [DUOLabs333/Photopea-Offline#1]
The files do not publish it just says: 
![image](https://user-images.githubusercontent.com/45278020/103555900-f6e54b00-4e7e-11eb-9143-acc6624caae3.png)
 on the top.

**Comment by DUOLabs333** [comment]
Well, that makes sense if it is to be used offline, no?

**Comment by DUOLabs333** [comment]
Also, an aside, why did you create a copy of this repo and renamed it PhotoElement, instead of just forking it?

**Comment by WaltDisneyWorld** [comment]
For editing purposes. Secondly, is there any way it could save it?

**Comment by DUOLabs333** [comment]
Are you asking if there is a way for it to publish (and for the record, it works for me)?

**Comment by WaltDisneyWorld** [comment]
yeah, to like a site under my domain so like domain.com#484363 Just you know what I mean

**Comment by DUOLabs333** [comment]
Yes, but just to let you know, I don't think even Photopea allows for this. However, you could use a self-hosted alternative to imgur, like [cheverto](https://chevereto.com/free). Install it and set up the server, so it could work localhost. Then, add an option to the "Publish" menu (you are going to have to do it yourself, I'm only interested in making it offline), and add JavaScript so that when you click it, it encodes the current activeDocument in Base64 (can't be too hard-- a hacky way is to just take a screenshot of the document and base64 it. However, no recommended), and submit a POST request to your server (https://v3-docs.chevereto.com/API/V1.html, https://www.freecodecamp.org/news/here-is-the-most-popular-ways-to-make-an-http-request-in-javascript-954ce8c95aaa/). Then, after you get that working, use whatever service you got to buy the domain to point your IP address to that domain (remember to change that domain in the POST request to domain.com). That *should* work, or at least get you started (You're a developer right? I'm sure you can take it from here :) ).

Also, it would be domain.com/484363.

**Comment by DUOLabs333** [comment]
I am going to close this now.
