### ISSUE TITLE
Photopea broke something

### ISSUE THREAD

**Issue by r3nor** [DUOLabs333/Photopea-Offline#10]
I can't view the nixnet repo, do I need to get invited or something?

**Comment by r3nor** [comment]
I was able to clone it via rad, I'm not sure if that one is updated? I see the last commit there is from `Date:   Fri Mar 22 09:14:39 2024`

**Comment by DUOLabs333** [comment]
Yeah, apparently, my repo was too big for nixnet so the host deleted it. However, even after shrinking it (I removed all fonts from the history), it still wouldn't allow me to recreate the repo. I tried reaching out to the host, but I haven't received a response. So, I set up a Radicle mirror.

The Radicle mirror is the official one at this moment --- I only update it when I push a fix to Updater.py. Since no one opened up any issues about breakage, I saw no reason to update the repo.

**Comment by r3nor** [comment]
nice, I just tested Updater.py and it broke completely, I went back to the original Radicle version

**Comment by DUOLabs333** [comment]
Are you saying that the Updater.py on Radicle doesn't work?

**Comment by r3nor** [comment]
@DUOLabs333 Photopea changed something that broke the Updater yeah, check out https://photopea.com and you'll see... or just try the Updater.py

**Comment by DUOLabs333** [comment]
Ah, I see the issue --- Photopea no longer has a stable name for all of its resources (don't know why they did that), but now generates them using a Javascript function. Right now, I can get around it with a regex, but at some point, I may have to start using a Javascript interpreter (ie, load page in Selenium, see the urls it tries to download, and just copy that).

**Comment by DUOLabs333** [comment]
Ok, I think my fix works.

**Comment by DUOLabs333** [comment]
I pushed my fix --- I'm not sure how long it takes to sync with the Radicle network, so check back in an hour.

**Comment by r3nor** [comment]
I think it's not been synced yet, I do `rad sync --fetch` and only 2 seeds are serving it, maybe your rad node needs to be online and I'm pulling from nodes that have not yet synced

**Comment by DUOLabs333** [comment]
Hmmm, it seems that my node didn't connect to anyone else. I'll see if I can debug this. If not, I may have to migrate to codeberg (they don't respect DMCA, right?)

**Comment by DUOLabs333** [comment]
I switched to using codeberg. See if you can access the updated repo now.
